### ISSUE TITLE
Feature request: Scroll on pinned columns

### ISSUE THREAD

**Issue by scotthovestadt** [ceolter/angular-grid#398]
It's a common request from users to be able to scroll on the pinned columns.

**Comment by scotthovestadt** [comment]
I don't actually think this will be that hard to implement with the current way you have it setup. It's a very simple change. Here is how I have it working (with jQuery, but I can port it). Would you like me to submit a PR? Is this something you would merge?

Basically, you are syncing the scroll using CSS "top" right now. I disable that, and sync between using the scrollTop attribute.

JS
````
// Sync scroll between pinned colums and body columns
var pinnedViewport = $('.ag-pinned-cols-viewport');
var bodyViewport = $('.ag-body-viewport');
pinnedViewport.on('scroll', function onPinnedScroll(e) {
  bodyViewport.scrollTop(pinnedViewport.scrollTop());
});
bodyViewport.on('scroll', function onPinnedScroll(e) {
  pinnedViewport.scrollTop(bodyViewport.scrollTop());
});
````

CSS
````
/* Allow pinned columns to scroll (JS handles sync) */
.ag-pinned-cols-container {
  top: 0 !important;
}
.ag-pinned-cols-viewport {
  overflow-y: scroll !important;
  height: 100% !important;
}
````

**Comment by scotthovestadt** [comment]
@ceolter Let me know what you think. A better way of doing this might be to remove both viewports and scroll them together, while having only a horizontal viewport for the body columns. It'd be a smoother scrolling experience... That would require a major refactor of a lot of pieces though.

**Comment by ceolter** [comment]
> A better way of doing this might be to remove both viewports and scroll them together, while having only a horizontal viewport for the body columns. It'd be a smoother scrolling experience... That would require a major refactor of a lot of pieces though.


that won't work well, because the non-pinned has to scroll independently of the pinned when scrolling horizontally.

i put a lot of time into getting the basic scrolling working. the pinned section has a lot in common with the header. basically the pinned scrolls vertically with the body but doesn't scroll horizontally, and the header scrolls horizontally with the body but doesn't scroll vertically. it works very well, just some minor quirks  such as the mouse wheel. doing it another way would just introduce other quirks i'm sure as i did PoC some other options when coming up with the current design.

**Comment by scotthovestadt** [comment]
@ceolter OK, makes sense. The way I've implemented this is not very different from what you did.

The mouse wheel not scrolling pinned columns is not a minor quirk for my use-case. With the existing grid I'm replacing, SlickGrid, which has similar behavior (mouse wheel doesn't scroll because pinned columns were an afterthought in that grid), not being able to scroll on the pinned columns are the number ONE user complaint.

I'll do another pass on this today to see if I can identify any quirks and test in a few more browsers. I was thinking it might be safer to assign the height of the elements manually so I could subtract the 25 pixels for the header from them.

If I can get this feature into a stable place, would you consider merging it in?

**Comment by ceolter** [comment]
> If I can get this feature into a stable place, would you consider merging it in?

i haven't had a chance to look at your code yet. assuming the code is fine, then yes i'll consider merging it.

i've spent about 4hrs today going through another PR and rewriting code!!! so didn't get to your one (and i'm still not finished with the other).

if you want to wait for me to take a look before you continue (stop you doing something i don't accept) then by all means. i should get a chance over this weekend.

**Comment by ceolter** [comment]
btw - very interested to hear your comparisons with slick grid, not just with this feature, but in general. i was not a heavy slick grid user - so am particularly interested into why you are using ag-grid over slickgrid. in my head, slickgrid is pretty dam good!!! (but as i said, i've never used it in anger).

**Comment by scotthovestadt** [comment]
@ceolter There is a small bug with my PR - when you scroll all the way to the bottom, the container that contains both pinned and body columns scrolls and the header disappears. To fix it, I think the height of the inner containers needs to be set manually (not to 100%) but I'm not sure of the proper place to do it in the code.

Instead of having you review this code, I think a better PR would be to implement the following. I'm willing to do it, if you approve the design. Can you take a look?:

![image](https://cloud.githubusercontent.com/assets/1831484/9530538/4d859c7a-4cb5-11e5-9fb0-e8303ecef615.png)

If you don't want to implement this design, I'll work on fixing the bug with the existing PR, which is much less of a change to the existing structure.

**Comment by ceolter** [comment]
i have just checked in a fix for #14, isn't this what you are looking for???

basically i just add a mouse wheel listener to the pinned columns, and scroll when i get notified.

**Comment by scotthovestadt** [comment]
Perfect. You can close.
